inherit_gem:
  syntax_tree: config/rubocop.yml

AllCops:
  TargetRubyVersion: 2.6.0
  NewCops: enable
  UseCache: true
  Exclude:
    - hbase/**/*
    - script/**/*
    - vendor/**/*

Layout/LineLength:
  Max: 120

Lint/AssignmentInCondition:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/ShadowedException:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Lint/StructNewOverride:
  Enabled: true

Lint/UnusedMethodArgument:
  Enabled: false

Lint/Void:
  Exclude:
    - spec/**/*

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - moneta.gemspec

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/ConstantName:
  Exclude:
    - lib/rack/cache/moneta.rb

Naming/RescuedExceptionsVariableName:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Security/MarshalLoad:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/CharacterLiteral:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - spec/moneta/adapters/cassandra/helper.rb

Style/FrozenStringLiteralComment:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/MutableConstant:
  Exclude:
    - lib/rack/cache/moneta.rb

Style/NilComparison:
  EnforcedStyle: comparison

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/NonNilCheck:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/PreferredHashMethods:
  Enabled: false

Style/RescueStandardError:
  EnforcedStyle: implicit

Style/RescueModifier:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/YodaCondition:
  Enabled: false
