# Generated by generate.rb
require 'helper'

describe_juno "adapter_riak" do
  require 'riak'

  Riak.disable_list_keys_warnings = true

  def new_store
    Juno::Adapters::Riak.new
  end

  include_context 'setup_store'
  it_should_behave_like 'null_stringkey_stringvalue'
  it_should_behave_like 'store_stringkey_stringvalue'
  it_should_behave_like 'returndifferent_stringkey_stringvalue'
end
