# Generated by generate.rb
require 'helper'

describe_juno "adapter_leveldb" do
  def new_store
    Juno::Adapters::LevelDB.new(:dir => File.join(make_tempdir, "adapter_leveldb"))
  end

  include_context 'setup_store'
  it_should_behave_like 'null_stringkey_stringvalue'
  it_should_behave_like 'store_stringkey_stringvalue'
  it_should_behave_like 'returndifferent_stringkey_stringvalue'
end
