# Generated by generate.rb
require 'helper'

describe_juno "cache_memory_null" do
  def new_store
    Juno.build do
      use(:Cache) do
        backend(Juno::Adapters::Memory.new)
        cache(Juno::Adapters::Null.new)
      end
    end
  end

  include_context 'setup_store'
  it_should_behave_like 'null_stringkey_stringvalue'
  it_should_behave_like 'store_stringkey_stringvalue'
  it_should_behave_like 'returndifferent_stringkey_stringvalue'
end
