# Generated by generate.rb
require 'helper'

describe_juno "adapter_mongo" do
  def new_store
    Juno::Adapters::Mongo.new(:db => "adapter_mongo")
  end

  include_context 'setup_store'
  it_should_behave_like 'null_stringkey_stringvalue'
  it_should_behave_like 'store_stringkey_stringvalue'
  it_should_behave_like 'returndifferent_stringkey_stringvalue'
end
