# Generated by generate.rb at 2012-12-02 15:00:09 +0100, heads/master-0-gab73edc
require 'helper'

begin
  require 'fog'
  Fog.mock!
  store = Juno::Adapters::Fog.new(:aws_access_key_id => 'fake_access_key_id',
      :aws_secret_access_key  => 'fake_secret_access_key',
      :provider               => 'AWS',
      :dir                    => 'juno')
  store['foo'] = 'bar'
  store.clear
  store.close

  describe "adapter_fog" do
    let(:store) do
      Juno::Adapters::Fog.new(:aws_access_key_id => 'fake_access_key_id',
          :aws_secret_access_key  => 'fake_secret_access_key',
          :provider               => 'AWS',
          :dir                    => 'juno')
    end

    include_context 'juno_store'
    it_should_behave_like 'null_stringkey_stringvalue'
    it_should_behave_like 'store_stringkey_stringvalue'
    it_should_behave_like 'returndifferent_stringkey_stringvalue'
  end
rescue LoadError => ex
  puts "\e[31mTest adapter_fog not executed: #{ex.message}\e[0m"
rescue Exception => ex
  puts "\e[31mTest adapter_fog not executed: #{ex.message}\e[0m"
  puts ex.backtrace.join("\n")
end
