# Generated by generate.rb at 2012-12-02 15:00:09 +0100, heads/master-0-gab73edc
require 'helper'

begin
  store = Juno.build do
    use(:Cache) do
      backend { adapter :File, :dir => File.join(make_tempdir, "cache_file_memory") }
      cache { adapter :Memory }
    end
  end
  store['foo'] = 'bar'
  store.clear
  store.close

  describe "cache_file_memory" do
    let(:store) do
      Juno.build do
        use(:Cache) do
          backend { adapter :File, :dir => File.join(make_tempdir, "cache_file_memory") }
          cache { adapter :Memory }
        end
      end
    end

    include_context 'juno_store'
    it_should_behave_like 'null_stringkey_stringvalue'
    it_should_behave_like 'store_stringkey_stringvalue'
    it_should_behave_like 'returndifferent_stringkey_stringvalue'
    it 'should store loaded values in cache' do
      store.backend['foo'] = 'bar'
      store.cache['foo'].should == nil
      store['foo'].should == 'bar'
      store.cache['foo'].should == 'bar'
      store.backend.delete('foo')
      store['foo'].should == 'bar'
      store.delete('foo')
      store['foo'].should == nil
    end

  end
rescue LoadError => ex
  puts "\e[31mTest cache_file_memory not executed: #{ex.message}\e[0m"
rescue Exception => ex
  puts "\e[31mTest cache_file_memory not executed: #{ex.message}\e[0m"
  puts ex.backtrace.join("\n")
end
