# Generated by generate.rb at 2012-12-02 15:00:09 +0100, heads/master-0-gab73edc
require 'helper'

begin
  store = Juno.build do
    use :Proxy
    use :Expires
    use :Proxy
    adapter :Memory
  end
  store['foo'] = 'bar'
  store.clear
  store.close

  describe "proxy_expires_memory" do
    let(:store) do
      Juno.build do
        use :Proxy
        use :Expires
        use :Proxy
        adapter :Memory
      end
    end

    include_context 'juno_store'
    it_should_behave_like 'null_objectkey_objectvalue'
    it_should_behave_like 'null_objectkey_stringvalue'
    it_should_behave_like 'null_objectkey_hashvalue'
    it_should_behave_like 'null_stringkey_objectvalue'
    it_should_behave_like 'null_stringkey_stringvalue'
    it_should_behave_like 'null_stringkey_hashvalue'
    it_should_behave_like 'null_hashkey_objectvalue'
    it_should_behave_like 'null_hashkey_stringvalue'
    it_should_behave_like 'null_hashkey_hashvalue'
    it_should_behave_like 'store_objectkey_objectvalue'
    it_should_behave_like 'store_objectkey_stringvalue'
    it_should_behave_like 'store_objectkey_hashvalue'
    it_should_behave_like 'store_stringkey_objectvalue'
    it_should_behave_like 'store_stringkey_stringvalue'
    it_should_behave_like 'store_stringkey_hashvalue'
    it_should_behave_like 'store_hashkey_objectvalue'
    it_should_behave_like 'store_hashkey_stringvalue'
    it_should_behave_like 'store_hashkey_hashvalue'
    it_should_behave_like 'expires_objectkey_objectvalue'
    it_should_behave_like 'expires_objectkey_stringvalue'
    it_should_behave_like 'expires_objectkey_hashvalue'
    it_should_behave_like 'expires_stringkey_objectvalue'
    it_should_behave_like 'expires_stringkey_stringvalue'
    it_should_behave_like 'expires_stringkey_hashvalue'
    it_should_behave_like 'expires_hashkey_objectvalue'
    it_should_behave_like 'expires_hashkey_stringvalue'
    it_should_behave_like 'expires_hashkey_hashvalue'
  end
rescue LoadError => ex
  puts "\e[31mTest proxy_expires_memory not executed: #{ex.message}\e[0m"
rescue Exception => ex
  puts "\e[31mTest proxy_expires_memory not executed: #{ex.message}\e[0m"
  puts ex.backtrace.join("\n")
end
