# Generated by generate.rb at 2012-12-02 15:58:06 +0100, heads/master-0-g7a551c7
require 'helper'

describe_juno "stack_file_memory" do
  def new_store
    Juno.build do
      use(:Stack) do
        add(Juno.new(:Null))
        add(Juno::Adapters::Null.new)
        add { adapter :File, :dir => File.join(make_tempdir, "stack-file1") }
        add { adapter :Memory }
      end
    end
  end

  include_context 'setup_store'
  it_should_behave_like 'null_stringkey_stringvalue'
  it_should_behave_like 'store_stringkey_stringvalue'
  it_should_behave_like 'returndifferent_stringkey_stringvalue'
end
