# Generated by generate.rb at 2012-12-02 15:00:09 +0100, heads/master-0-gab73edc
require 'helper'

begin
  store = Juno.build do
    use(:Stack) do
      add(Juno.new(:Null))
      add(Juno::Adapters::Null.new)
      add { adapter :File, :dir => File.join(make_tempdir, "stack-file1") }
      add { adapter :Memory }
    end
  end
  store['foo'] = 'bar'
  store.clear
  store.close

  describe "stack_file_memory" do
    let(:store) do
      Juno.build do
        use(:Stack) do
          add(Juno.new(:Null))
          add(Juno::Adapters::Null.new)
          add { adapter :File, :dir => File.join(make_tempdir, "stack-file1") }
          add { adapter :Memory }
        end
      end
    end

    include_context 'juno_store'
    it_should_behave_like 'null_stringkey_stringvalue'
    it_should_behave_like 'store_stringkey_stringvalue'
    it_should_behave_like 'returndifferent_stringkey_stringvalue'
  end
rescue LoadError => ex
  puts "\e[31mTest stack_file_memory not executed: #{ex.message}\e[0m"
rescue Exception => ex
  puts "\e[31mTest stack_file_memory not executed: #{ex.message}\e[0m"
  puts ex.backtrace.join("\n")
end
