#!/bin/bash
set -e

# Reconfigure CouchDB to use delayed commits for speed: http://guide.couchdb.org/draft/performance.html
sudo sed -i '/\[couchdb\]/a delayed_commits = true' /etc/couchdb/local.ini
sudo systemctl restart couchdb

# Display some info about CouchDB
sudo systemctl status couchdb

sleep 1
curl -X PUT http://127.0.0.1:5984/_users
curl -X PUT http://127.0.0.1:5984/_replicator

