#!/bin/bash
sudo service riak start
sudo service couchdb start
sudo service redis-server start
sudo service cassandra start
sudo service memcached start
sudo service mongodb start
/usr/sbin/ttserver -dmn
sleep 3
