#!/bin/bash

# Reconfigure CouchDB to use delayed commits for speed: http://guide.couchdb.org/draft/performance.html
sudo sed -i '/\[couchdb\]/a delayed_commits = true' /etc/couchdb/local.ini
sudo service couchdb start

# Start HBase
$(dirname $0)/start-hbase

# Waiting for servers to start
sleep 3
