# Generated by generate.rb
require 'helper'

describe_moneta "adapter_client" do
  Moneta::Server.new(Moneta.new(:Memory)) rescue nil
  def new_store
    Moneta::Adapters::Client.new
  end

  include_context 'setup_store'
  it_should_behave_like 'null_stringkey_stringvalue'
  it_should_behave_like 'store_stringkey_stringvalue'
  it_should_behave_like 'returndifferent_stringkey_stringvalue'
end
