# Generated by generate.rb
require 'helper'

describe_moneta "adapter_fog" do
  require 'fog'
  Fog.mock!
  def new_store
    Moneta::Adapters::Fog.new(:aws_access_key_id => 'fake_access_key_id',
        :aws_secret_access_key  => 'fake_secret_access_key',
        :provider               => 'AWS',
        :dir                    => 'moneta')
  end

  include_context 'setup_store'
  it_should_behave_like 'null_stringkey_stringvalue'
  it_should_behave_like 'store_stringkey_stringvalue'
  it_should_behave_like 'returndifferent_stringkey_stringvalue'
end
