# Generated by generate-specs
require 'helper'

describe_moneta "adapter_couch" do
  def features
    [:create]
  end

  def new_store
    Moneta::Adapters::Couch.new(:db => 'adapter_couch')
  end

  def load_value(value)
    Marshal.load(value)
  end

  include_context 'setup_store'
  it_should_behave_like 'concurrent_create'
  it_should_behave_like 'create'
  it_should_behave_like 'features'
  it_should_behave_like 'multiprocess'
  it_should_behave_like 'not_increment'
  it_should_behave_like 'null_simplestringkey_stringvalue'
  it_should_behave_like 'null_simplestringkey_hashvalue'
  it_should_behave_like 'null_simplestringkey_integervalue'
  it_should_behave_like 'persist_simplestringkey_stringvalue'
  it_should_behave_like 'persist_simplestringkey_hashvalue'
  it_should_behave_like 'persist_simplestringkey_integervalue'
  it_should_behave_like 'returndifferent_simplestringkey_stringvalue'
  it_should_behave_like 'returndifferent_simplestringkey_hashvalue'
  it_should_behave_like 'store_simplestringkey_stringvalue'
  it_should_behave_like 'store_simplestringkey_hashvalue'
  it_should_behave_like 'store_simplestringkey_integervalue'
  it_should_behave_like 'store_large'
end
