# Generated by generate.rb
require 'helper'

describe_moneta "expires_memory" do
  def new_store
    Moneta.build do
      use :Expires
      adapter :Memory
    end
  end

  def load_value(value)
    Marshal.load(value)
  end

  include_context 'setup_store'
  it_should_behave_like 'null_objectkey_objectvalue'
  it_should_behave_like 'null_objectkey_stringvalue'
  it_should_behave_like 'null_objectkey_hashvalue'
  it_should_behave_like 'null_objectkey_booleanvalue'
  it_should_behave_like 'null_stringkey_objectvalue'
  it_should_behave_like 'null_stringkey_stringvalue'
  it_should_behave_like 'null_stringkey_hashvalue'
  it_should_behave_like 'null_stringkey_booleanvalue'
  it_should_behave_like 'null_hashkey_objectvalue'
  it_should_behave_like 'null_hashkey_stringvalue'
  it_should_behave_like 'null_hashkey_hashvalue'
  it_should_behave_like 'null_hashkey_booleanvalue'
  it_should_behave_like 'store_objectkey_objectvalue'
  it_should_behave_like 'store_objectkey_stringvalue'
  it_should_behave_like 'store_objectkey_hashvalue'
  it_should_behave_like 'store_objectkey_booleanvalue'
  it_should_behave_like 'store_stringkey_objectvalue'
  it_should_behave_like 'store_stringkey_stringvalue'
  it_should_behave_like 'store_stringkey_hashvalue'
  it_should_behave_like 'store_stringkey_booleanvalue'
  it_should_behave_like 'store_hashkey_objectvalue'
  it_should_behave_like 'store_hashkey_stringvalue'
  it_should_behave_like 'store_hashkey_hashvalue'
  it_should_behave_like 'store_hashkey_booleanvalue'
  it_should_behave_like 'expires_objectkey_objectvalue'
  it_should_behave_like 'expires_objectkey_stringvalue'
  it_should_behave_like 'expires_objectkey_hashvalue'
  it_should_behave_like 'expires_objectkey_booleanvalue'
  it_should_behave_like 'expires_stringkey_objectvalue'
  it_should_behave_like 'expires_stringkey_stringvalue'
  it_should_behave_like 'expires_stringkey_hashvalue'
  it_should_behave_like 'expires_stringkey_booleanvalue'
  it_should_behave_like 'expires_hashkey_objectvalue'
  it_should_behave_like 'expires_hashkey_stringvalue'
  it_should_behave_like 'expires_hashkey_hashvalue'
  it_should_behave_like 'expires_hashkey_booleanvalue'
  it_should_behave_like 'increment'
end
