# Generated by generate.rb
require 'helper'

describe_moneta "simple_memory_with_json_serializer" do
  def new_store
    Moneta.new(:Memory, :serializer => :json, :logger => {:out => File.open(File.join(make_tempdir, 'simple_memory_with_json_serializer.log'), 'a')})
  end

  def load_value(value)
    ::MultiJson.load(value).first
  end

  include_context 'setup_store'
  it_should_behave_like 'null_hashkey_hashvalue'
  it_should_behave_like 'null_hashkey_stringvalue'
  it_should_behave_like 'null_stringkey_hashvalue'
  it_should_behave_like 'null_stringkey_stringvalue'
  it_should_behave_like 'store_hashkey_hashvalue'
  it_should_behave_like 'store_hashkey_stringvalue'
  it_should_behave_like 'store_stringkey_hashvalue'
  it_should_behave_like 'store_stringkey_stringvalue'
  it_should_behave_like 'returndifferent_hashkey_hashvalue'
  it_should_behave_like 'returndifferent_hashkey_stringvalue'
  it_should_behave_like 'returndifferent_stringkey_hashvalue'
  it_should_behave_like 'returndifferent_stringkey_stringvalue'
  it_should_behave_like 'transform_value'
  it_should_behave_like 'increment'
end
