# Generated by generate.rb
require 'helper'

describe_moneta "transformer_bzip2" do
  def new_store
    Moneta.build do
      use :Transformer, :value => :bzip2
      adapter :Memory
    end
  end

  def load_value(value)
    ::Bzip2.uncompress(value)
  end

  include_context 'setup_store'
  it_should_behave_like 'null_objectkey_stringvalue'
  it_should_behave_like 'null_stringkey_stringvalue'
  it_should_behave_like 'null_hashkey_stringvalue'
  it_should_behave_like 'store_objectkey_stringvalue'
  it_should_behave_like 'store_stringkey_stringvalue'
  it_should_behave_like 'store_hashkey_stringvalue'
  it_should_behave_like 'returndifferent_objectkey_stringvalue'
  it_should_behave_like 'returndifferent_stringkey_stringvalue'
  it_should_behave_like 'returndifferent_hashkey_stringvalue'
  it_should_behave_like 'transform_value'
end
