# Generated by generate.rb
require 'helper'

describe_moneta "transformer_msgpack" do
  def new_store
    Moneta.build do
      use :Transformer, :key => :msgpack, :value => :msgpack
      adapter :Memory
    end
  end

  include_context 'setup_store'
  it_should_behave_like 'null_hashkey_hashvalue'
  it_should_behave_like 'null_hashkey_stringvalue'
  it_should_behave_like 'null_stringkey_hashvalue'
  it_should_behave_like 'null_stringkey_stringvalue'
  it_should_behave_like 'store_hashkey_hashvalue'
  it_should_behave_like 'store_hashkey_stringvalue'
  it_should_behave_like 'store_stringkey_hashvalue'
  it_should_behave_like 'store_stringkey_stringvalue'
  it_should_behave_like 'returndifferent_hashkey_hashvalue'
  it_should_behave_like 'returndifferent_hashkey_stringvalue'
  it_should_behave_like 'returndifferent_stringkey_hashvalue'
  it_should_behave_like 'returndifferent_stringkey_stringvalue'
  it 'should transform value' do
    store['key'] = 'value'
    store.load('key', :raw => true).should == ::MessagePack.pack('value')
  end
end
